language: python

sudo: required

cache:
  - pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION=1.11.*
  - DJANGO_VERSION=2.0.*

matrix:
  exclude:
  - python: "2.7"
    env: DJANGO_VERSION=2.0.*

install:
  - pip install flake8 coverage coveralls

script:
  - flake8 django-choice
  - coverage run setup.py test
  - coverage report -m

after_success:
  - coveralls
